#!/usr/bin/env python3
"""
run.py  –  Local CLI for the YouTube-to-Transcript GitHub Actions workflow.

Usage:
    python run.py <url1> [url2] [url3] ...

What it does:
  1. Validates that `gh` (GitHub CLI) is installed and authenticated.
  2. Detects the current GitHub repository from `git remote`.
  3. Triggers the `transcribe.yml` workflow (two parallel jobs).
  4. Polls both jobs independently:
       - As soon as the fast job (captions + Supadata) finishes, downloads
         and prints those transcripts immediately.
       - Continues polling the Whisper job in the background and downloads
         its transcripts when it finishes.
  5. All output lands in ./downloads/ (previous run is replaced).

Requirements:
    gh CLI  (https://cli.github.com) – installed and `gh auth login` run.
"""

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from datetime import datetime
from pathlib import Path


# ---------------------------------------------------------------------------
# Colour helpers
# ---------------------------------------------------------------------------
_USE_COLOR = sys.stdout.isatty() and os.name != "nt"

def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _USE_COLOR else text

def ok(msg):    print(_c("32",  f"[✓] {msg}"))
def info(msg):  print(_c("36",  f"[→] {msg}"))
def warn(msg):  print(_c("33",  f"[!] {msg}"))
def err(msg):   print(_c("31",  f"[✗] {msg}"))
def head(msg):  print(_c("1",   f"\n{'='*60}\n  {msg}\n{'='*60}"))


# ---------------------------------------------------------------------------
# Shell helpers
# ---------------------------------------------------------------------------

def run_cmd(cmd: list[str], capture=True, check=True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=capture, text=True, check=check)


def gh(*args, capture=True, check=True) -> subprocess.CompletedProcess:
    return run_cmd(["gh", *args], capture=capture, check=check)


# ---------------------------------------------------------------------------
# Pre-flight
# ---------------------------------------------------------------------------

def check_gh_installed():
    if shutil.which("gh") is None:
        err("GitHub CLI (gh) is not installed. See https://cli.github.com")
        sys.exit(1)
    ok("gh CLI found.")


def check_gh_auth():
    if gh("auth", "status", check=False).returncode != 0:
        err("Not authenticated. Run: gh auth login")
        sys.exit(1)
    ok("gh CLI authenticated.")


def detect_repo() -> str:
    try:
        remote = run_cmd(["git", "remote", "get-url", "origin"]).stdout.strip()
    except subprocess.CalledProcessError:
        err("Could not read git remote 'origin'.")
        sys.exit(1)
    match = re.search(r"github\.com[:/](.+?)(?:\.git)?$", remote)
    if not match:
        err(f"Remote doesn't look like a GitHub repo: {remote}")
        sys.exit(1)
    repo = match.group(1)
    ok(f"Repository: {repo}")
    return repo


# ---------------------------------------------------------------------------
# YouTube cookie extraction + GitHub Secret sync
# ---------------------------------------------------------------------------

def extract_and_sync_cookies(repo: str) -> bool:
    """
    Use yt-dlp to decrypt and export Chrome's YouTube cookies to a Netscape
    cookie file, then push the contents to the YOUTUBE_COOKIES GitHub Secret.

    yt-dlp handles all macOS Keychain decryption internally via
    --cookies-from-browser, so no manual crypto is needed.

    Returns True if cookies were successfully synced.
    """
    if shutil.which("yt-dlp") is None:
        warn("yt-dlp not found locally — skipping cookie sync.")
        warn("Install with: pip install yt-dlp")
        return False

    info("Extracting YouTube cookies from Chrome …")
    info("(macOS may show a Keychain access prompt — click Allow)")

    # yt-dlp requires the cookie file to already exist and contain the
    # Netscape header — it appends to it rather than creating from scratch.
    fd, cookies_path = tempfile.mkstemp(suffix=".txt", prefix="yt_cookies_")
    try:
        # Pre-seed with the required Netscape header
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by yt-dlp.\n\n")

        result = subprocess.run(
            [
                "yt-dlp",
                "--cookies-from-browser", "chrome",
                "--cookies", cookies_path,
                "--skip-download",
                "--quiet",
                "--no-warnings",
                "https://www.youtube.com/watch?v=dQw4w9WgXcQ",  # real video URL needed
            ],
            capture_output=True,
            text=True,
            timeout=60,
        )

        cookie_text = Path(cookies_path).read_text(encoding="utf-8")

        # Must have actual cookie data lines (tab-separated Netscape rows)
        data_lines = [l for l in cookie_text.splitlines()
                      if l.strip() and not l.startswith("#")]

        if not data_lines:
            warn(f"No cookie data extracted. yt-dlp stderr:\n  {result.stderr.strip()[:400]}")
            return False

        # Count YouTube/Google entries specifically
        yt_lines = [l for l in data_lines
                    if "youtube.com" in l or "google.com" in l]
        ok(f"Extracted {len(data_lines)} total cookies ({len(yt_lines)} YouTube/Google).")

        if len(yt_lines) == 0:
            warn("No YouTube cookies found — are you logged into YouTube in Chrome?")
            return False

        # Push to GitHub Secret
        info(f"Syncing YOUTUBE_COOKIES secret to {repo} …")
        set_result = subprocess.run(
            ["gh", "secret", "set", "YOUTUBE_COOKIES",
             "--repo", repo,
             "--body", cookie_text],
            capture_output=True,
            text=True,
        )

        if set_result.returncode != 0:
            warn(f"Failed to set secret: {set_result.stderr.strip()[:300]}")
            return False

        ok("YOUTUBE_COOKIES secret updated successfully.")
        return True

    except subprocess.TimeoutExpired:
        warn("Cookie extraction timed out (60s). Is Chrome running and unlocked?")
        return False
    except Exception as e:
        warn(f"Cookie extraction failed: {e}")
        return False
    finally:
        try:
            os.unlink(cookies_path)
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Trigger workflow
# ---------------------------------------------------------------------------

def trigger_workflow(repo: str, urls: list[str]) -> str:
    """Trigger the workflow and return the new run ID."""
    workflow_file = "transcribe.yml"
    before_ids = _list_run_ids(repo, workflow_file)

    info(f"Triggering workflow with {len(urls)} URL(s) …")
    gh(
        "workflow", "run", workflow_file,
        "--repo", repo,
        "--field", f"youtube_urls={' '.join(urls)}",
    )

    info("Waiting for run to be registered …")
    for attempt in range(30):
        time.sleep(3)
        after_ids = _list_run_ids(repo, workflow_file)
        new_ids = [r for r in after_ids if r not in before_ids]
        if new_ids:
            run_id = new_ids[0]
            ok(f"Run started: {run_id}")
            print(f"  https://github.com/{repo}/actions/runs/{run_id}")
            return run_id
        if attempt % 5 == 4:
            info(f"  Still waiting … ({(attempt+1)*3}s)")

    err("Timed out waiting for the workflow run to appear.")
    sys.exit(1)


def _list_run_ids(repo: str, workflow_file: str) -> list[str]:
    result = gh("run", "list", "--repo", repo, "--workflow", workflow_file,
                "--limit", "10", "--json", "databaseId", check=False)
    if result.returncode != 0:
        return []
    try:
        return [str(item["databaseId"]) for item in json.loads(result.stdout)]
    except Exception:
        return []


# ---------------------------------------------------------------------------
# Job status helpers
# ---------------------------------------------------------------------------

TERMINAL = {"completed", "failure", "cancelled", "timed_out", "skipped"}

# Maps artifact name → human label
ARTIFACTS = {
    "transcripts-fast":    "Fast (captions + Supadata)",
    "transcripts-whisper": "Whisper (audio → text)",
}

# Maps job *display name* (the `name:` field in the workflow YAML) to artifact name.
# These must match the `name:` values under `jobs:` in transcribe.yml exactly.
JOB_TO_ARTIFACT = {
    "Fast Transcript (captions + Supadata)": "transcripts-fast",
    "Whisper Transcript (audio → text)":     "transcripts-whisper",
}


def get_jobs_status(repo: str, run_id: str) -> dict[str, dict]:
    """
    Returns a dict keyed by job name with keys: status, conclusion.
    """
    result = gh(
        "run", "view", run_id,
        "--repo", repo,
        "--json", "jobs",
        check=False,
    )
    if result.returncode != 0:
        return {}
    try:
        jobs = json.loads(result.stdout).get("jobs", [])
        return {
            j["name"]: {"status": j.get("status", ""), "conclusion": j.get("conclusion") or ""}
            for j in jobs
        }
    except Exception:
        return {}


def job_is_done(job: dict) -> bool:
    return job.get("status") in TERMINAL or job.get("conclusion") in TERMINAL


def job_succeeded(job: dict) -> bool:
    return job.get("conclusion") == "success"


# ---------------------------------------------------------------------------
# Download a single named artifact
# ---------------------------------------------------------------------------

def download_artifact(repo: str, run_id: str, artifact_name: str, dest: Path) -> bool:
    """Download one artifact by name into dest/. Returns True on success."""
    result = gh(
        "run", "download", run_id,
        "--repo", repo,
        "--name", artifact_name,
        "--dir", str(dest),
        check=False,
    )
    if result.returncode != 0:
        warn(f"Could not download '{artifact_name}': {result.stderr.strip()[:200]}")
        return False
    return True


# ---------------------------------------------------------------------------
# Print transcript files from a directory
# ---------------------------------------------------------------------------

def print_transcripts(artifact_dir: Path, label: str):
    head(f"RESULTS — {label}")

    summary_files = list(artifact_dir.rglob("summary.json"))
    txt_files     = sorted(f for f in artifact_dir.rglob("*.txt")
                           if f.name != "summary.json")

    # Print summary table
    for sf in summary_files:
        try:
            data = json.loads(sf.read_text(encoding="utf-8"))
            print(f"  {'Video ID':<15}  {'Source':<22}  {'Chars':>8}  Status")
            print(f"  {'-'*15}  {'-'*22}  {'-'*8}  ------")
            for item in data:
                vid = (item.get("video_id") or "?")[:15]
                # fast summary has "sources" dict; whisper summary has "chars"
                sources = item.get("sources")
                if sources:
                    for src, chars in sources.items():
                        print(f"  {vid:<15}  {src:<22}  {chars:>8,}  ✓")
                    if not sources:
                        print(f"  {vid:<15}  {'—':<22}  {'0':>8}  ✗  {item.get('error','')}")
                else:
                    chars = item.get("chars", 0)
                    status = "✓" if chars else "✗"
                    err_msg = item.get("error") or ""
                    print(f"  {vid:<15}  {'whisper':<22}  {chars:>8,}  {status}  {err_msg}")
        except Exception:
            pass

    # List files
    if txt_files:
        print(f"\n  Files:")
        for tf in txt_files:
            size = tf.stat().st_size
            print(f"    • {tf.relative_to(tf.parents[2])}  ({size:,} bytes)")
    else:
        warn("No .txt transcript files found in this artifact.")

    print()


# ---------------------------------------------------------------------------
# Main polling loop — watches both jobs, downloads each as it finishes
# ---------------------------------------------------------------------------

def poll_and_download(repo: str, run_id: str, downloads_dir: Path):
    """
    Poll both jobs. As soon as each job finishes, download its artifact
    and print the results inline. Returns when both jobs are done.
    """
    pending_jobs = set(JOB_TO_ARTIFACT.keys())   # jobs not yet downloaded
    downloaded   = set()
    spinner      = ["|", "/", "-", "\\"]
    tick         = 0
    start        = time.time()

    info("Polling jobs (fast job typically finishes in ~30–60s) …")
    print()

    while pending_jobs:
        time.sleep(8)
        tick += 1
        elapsed = int(time.time() - start)

        jobs = get_jobs_status(repo, run_id)

        # Build a compact status line
        JOB_SHORT = {
            "Fast Transcript (captions + Supadata)": "fast",
            "Whisper Transcript (audio → text)":     "whisper",
        }
        status_parts = []
        for jname in JOB_TO_ARTIFACT:
            j = jobs.get(jname, {})
            st = j.get("status", "queued")
            co = j.get("conclusion", "")
            display = co if co else st
            status_parts.append(f"{JOB_SHORT.get(jname, jname)}:{display}")

        print(
            f"\r  {spinner[tick % 4]}  [{elapsed}s]  "
            + "  |  ".join(status_parts)
            + "   ",
            end="", flush=True,
        )

        # Check each pending job
        for jname in list(pending_jobs):
            j = jobs.get(jname, {})
            if not job_is_done(j):
                continue

            # Job finished — download its artifact
            print()  # newline after spinner
            artifact_name = JOB_TO_ARTIFACT[jname]
            label         = ARTIFACTS[artifact_name]
            conclusion    = j.get("conclusion", "unknown")

            if job_succeeded(j):
                ok(f"Job '{jname}' finished ({elapsed}s). Downloading '{artifact_name}' …")
                artifact_dest = downloads_dir / artifact_name
                artifact_dest.mkdir(parents=True, exist_ok=True)
                if download_artifact(repo, run_id, artifact_name, artifact_dest):
                    print_transcripts(artifact_dest, label)
                    downloaded.add(jname)
                else:
                    warn(f"Artifact download failed for '{artifact_name}'.")
            else:
                warn(f"Job '{jname}' ended with: {conclusion}. Attempting artifact download anyway …")
                artifact_dest = downloads_dir / artifact_name
                artifact_dest.mkdir(parents=True, exist_ok=True)
                if download_artifact(repo, run_id, artifact_name, artifact_dest):
                    print_transcripts(artifact_dest, label)

            pending_jobs.discard(jname)

            # Resume spinner on next line if there are still pending jobs
            if pending_jobs:
                info("Still waiting for remaining job(s) …")

    print()  # final newline


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) < 2 or sys.argv[1] in ("-h", "--help"):
        print(__doc__)
        sys.exit(0)

    urls = [u.strip() for u in sys.argv[1:] if u.strip()]
    if not urls:
        err("No URLs provided.")
        sys.exit(1)

    head(f"YouTube → Transcript  |  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"  URLs ({len(urls)}):")
    for u in urls:
        print(f"    • {u}")
    print()

    check_gh_installed()
    check_gh_auth()
    repo = detect_repo()

    # Extract Chrome YouTube cookies and sync to GitHub Secret automatically
    extract_and_sync_cookies(repo)

    # Wipe downloads/ so previous run doesn't linger
    downloads_dir = Path("downloads")
    if downloads_dir.exists():
        shutil.rmtree(downloads_dir)
    downloads_dir.mkdir()

    run_id = trigger_workflow(repo, urls)

    poll_and_download(repo, run_id, downloads_dir)

    # Final summary
    head("ALL DONE")
    all_txt = sorted(downloads_dir.rglob("*.txt"))
    if all_txt:
        print(f"  {len(all_txt)} transcript file(s) in {downloads_dir.resolve()}:\n")
        for tf in all_txt:
            print(f"    • {tf.relative_to(downloads_dir)}  ({tf.stat().st_size:,} bytes)")
    else:
        warn("No transcript files were produced.")
    print()


if __name__ == "__main__":
    main()
